
<html>
	<head> 
		<?php echo $this->headScript(); ?>
	</head> 
	<body>

 	<?php
	        /*$auth= Zend_Auth::getInstance();
			if (!empty($auth) && ($auth instanceof Zend_Auth)) {  	     
	            $user= $auth->getStorage()->read();
	        	$role= $user['id_role'];
	        	//var_dump($user);
	        	$bootstrap = Zend_Controller_Front::getInstance()->getParam('bootstrap');
				$db= $bootstrap->getResource('db');
				$acl= new Login_Acl($db,$role);

	      echo '<li class="dir"><a href="#">Configuración</a><ul>';
	      if($acl->isAllowed($role,"roles"))
	        {
	             echo '<li><a href="/roles">Mensaje de Bienvenida</a></li>';
	        }
	      echo '</ul></li>';

	      echo '<li class="dir"><a href="#">Comandito (UBC)</a><ul>';
				//Menu comandito por mesa
				if($acl->isAllowed($role,"comandito/*"))
	  			{
		           echo '<li><a href="/comandito">Crear UBC por mesa</a></li>';
	        }
				
				//Menu comandito por centro
				if($acl->isAllowed($role,"comanditocentro/*"))
	  			{
		           echo '<li><a href="/comanditocentro">Crear UBC por centro</a></li>';
	        }*/


		?>

		<?php echo $this->layout()->content; ?>
	</body> 
</html>