<html>
	<head> 
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>

		<style type="text/css" title="currentStyle">
			@import "/st_rep/st/public/css/demo_page.css";
			@import "/st_rep/st/public/css/demo_table.css";
		</style>

		<script>
			 $(document).ready(function() {
			 	if( "<?php echo $this->msj_notification ?>" != "")
			 		notification("<?php echo $this->msj_notification ?>");
			 	if( "<?php echo $this->msj_error ?>" != "")
			 		error("<?php echo $this->msj_error ?>");
			});
		</script>

	</head> 
	<body>
		<!--<header>
			<a href="/st_rep/st/public/login/login/logout">Cerrar Sesión</a>
			<a href="/st_rep/st/public/login/login/login">Iniciar Sesión</a>
		</header>-->
		<section>
			<?php echo $this->layout()->content; ?>
		</section>
		
	</body> 
</html>