<style type="text/css">
p
{
	font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;
	text-align:center;
}
#ad
{
		margin: 0 auto;
        width: 800px;
    	border-bottom: 10px solid #999;
    	border-top: 10px solid #999;
   	/* padding-left:5px;*/
    	box-shadow: 7px 7px 7px #333;	
    	-webkit-box-shadow: 7px 7px 7px #333;/* chrome safari */
    	-moz-box-shadow: 7px 7px 7px #333;
	
}
#ad:hover
{
 	opacity:0.3;
}
.denegado 
{
	color:#FFF;
	font-size: 60px;
	text-shadow: #6374AB 3px 3px 2px;
	margin: 40px 0 40px 0;
}
.negro
{
	font-size: 20px;
}
.pequeno
{
	font-size: 10px;
}
.ensayo 
{
	width: 800px;
 	background:#E4E4E4;
	filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#CCC', endColorstr='#FFF');
	background: -webkit-gradient(linear, left top, left bottom, from(#CCC), to(#FFF)); 
	background: -moz-linear-gradient(top,  #CCC,  #FFF);
}
</style>

<div id="ad">
<table class="ensayo" CellSpacing="10" CellPadding="0">
  <tr>
    <td bgcolor="#ff5500"><p class="denegado">ACCESO DENEGADO</p></td>
  </tr>
  <tr>
    <td bgcolor="gray"><p class="negro"><strong>El acceso a la siguiente p&#225;gina ha sido denegado</strong></p>
                       <p class="pequeno">Por favor ponerse en contacto si usted cree que ha sido un error</p></td>
  </tr>
</table>
</div>