  <style>
  #feedback { font-size: 1.4em; }
  #selectable .ui-selecting { background: #FECA40; }
  #selectable .ui-selected { background: #F39814; color: white; }
  #selectable { list-style-type: none; margin: 0; padding: 0; width: 450px; }
  #selectable li { margin: 5px; padding: 3px; float: left; font-size: 4em; text-align: center; }
  </style>
<script>
  $(function() {
    $( "#selectable" ).selectable();
  });
</script>
